#! /bin/bash
# This is the expected entry point for Cockpit CI; will be called without
# arguments but with an appropriate $TEST_OS

set -eu

if [ -v TEST_SCENARIO ]; then
    [ "${TEST_SCENARIO}" = "${TEST_SCENARIO%%mobile}" ] || export TEST_MOBILE=true
fi

make check
make po/machines.pot
