#!/bin/sh
# image-customize script to prepare a bots VM for testing this application
# in TEST_SCENARIO=ws-container.
set -eux

# back up original ws image
podman tag quay.io/cockpit/ws:latest localhost/ws:released

# update ws container with our current code
cd /var/tmp
tar --strip-components=1 -xvf cockpit-machines*.tar.* cockpit-machines/dist

podman build -f - -t quay.io/cockpit/ws:latest . <<EOF
FROM quay.io/cockpit/ws
RUN rm -rf /usr/share/cockpit/machines
COPY dist /usr/share/cockpit/machines
EOF

# remove preinstalled rpms
dnf -C remove -y cockpit-bridge cockpit-ws

if systemctl is-active -q firewalld.service; then
    firewall-cmd --add-service=cockpit --permanent
fi
