#!/bin/sh
# image-customize script to prepare a a bots VM for cockpit-machines testing
set -eu

# for Debian based images, build and install debs
if [ -d /var/tmp/debian ]; then
    # build source package
    cd /var/tmp
    TAR=$(ls cockpit-machines-*.tar.xz)
    VERSION="${TAR#cockpit-machines-}"
    VERSION="${VERSION%.tar.xz}"
    ln -s $TAR cockpit-machines_${VERSION}.orig.tar.xz
    tar xf "$TAR"
    cd cockpit-machines
    cp -r ../debian .
    sed -i "s/(0-1)/(${VERSION}-1)/" debian/changelog
    dpkg-buildpackage -S -us -uc -nc

    # build and install binary package; prefer pbuilder if available (on Cockpit test VMs)
    if [ -e /var/cache/pbuilder/base.tgz ]; then
        pbuilder build --buildresult .. ../*.dsc
    else
        eatmydata apt-get install ${APT_INSTALL_OPTIONS:-} -y build-essential debhelper
        dpkg-buildpackage -us -uc -b
    fi
    dpkg -i ../*.deb

# install rpms
elif [ -e /var/tmp/*.rpm ]; then
    rpm -i --verbose /var/tmp/*.rpm
elif [ -d /var/tmp/arch ]; then
    # build source package
    cd /var/tmp
    TAR=$(ls cockpit-machines-*.tar.xz)
    VERSION="${TAR#cockpit-machines-}"
    VERSION="${VERSION%.tar.xz}"

    cp arch/PKGBUILD .
    sed -i "s/VERSION/$VERSION/" PKGBUILD; sed -i "s/SOURCE/$TAR/" PKGBUILD
    su builder -c "extra-x86_64-build"

    pacman -U --noconfirm *.pkg.tar.zst
fi

# for Debian images, allow libvirtd coredumps
if grep -q 'ID=debian' /etc/os-release; then
    echo '* soft core unlimited' >> /etc/security/limits.conf
fi

systemctl enable cockpit.socket

# don't force https:// (self-signed cert)
printf "[WebService]\\nAllowUnencrypted=true\\n" > /etc/cockpit/cockpit.conf

if type firewall-cmd >/dev/null 2>&1; then
    firewall-cmd --add-service=cockpit --permanent
fi
