#!/bin/sh
# image-customize script to prepare a a bots VM for cockpit-machines testing
set -eu

# for Debian images, allow libvirtd coredumps
if grep -q 'ID=debian' /usr/lib/os-release; then
    echo '* soft core unlimited' >> /etc/security/limits.conf
fi

systemctl enable cockpit.socket

# don't force https:// (self-signed cert)
mkdir -p /etc/cockpit
printf "[WebService]\\nAllowUnencrypted=true\\n" > /etc/cockpit/cockpit.conf

if systemctl is-active -q firewalld.service; then
    firewall-cmd --add-service=cockpit --permanent
fi
