specfile_path: cockpit-machines.spec
synced_files:
  - cockpit-machines.spec
upstream_package_name: cockpit-machines
downstream_package_name: cockpit-machines
actions:
  post-upstream-clone: make cockpit-machines.spec
  create-archive:
    - make dist DOWNLOAD_DIST_OPTIONS=--wait FORCE_DOWNLOAD_DIST=1
    - find -name 'cockpit-machines-*.tar.xz'
jobs:
  - job: tests
    trigger: pull_request
    metadata:
      targets:
      - fedora-34
      - fedora-35
      - fedora-rawhide
      - centos-stream-8
      - centos-stream-9
