upstream_project_url: https://github.com/cockpit-project/cockpit-machines
# enable notification of failed downstream jobs as issues
issue_repository: https://github.com/cockpit-project/cockpit-machines
specfile_path: cockpit-machines.spec
upstream_package_name: cockpit-machines
downstream_package_name: cockpit-machines
# use the nicely formatted release description from our upstream release, instead of git shortlog
copy_upstream_release_description: true

srpm_build_deps:
- jq
- make
- nodejs

actions:
  post-upstream-clone:
    - make node-cache dist

  fix-spec-file:
    # our locally built tarballs are not on the upstream releases page, point to the local files
    sed -i 's|^\(Source[0-9]*:\s*\).*\/|\1|' cockpit-machines.spec

  get-current-version: make print-version

jobs:
  - job: tests
    trigger: pull_request
    targets: &test_targets
      - fedora-42
      - fedora-43
      - fedora-rawhide
      - centos-stream-9
      - centos-stream-10

  - job: copr_build
    trigger: pull_request
    targets: *test_targets

  - job: copr_build
    trigger: release
    owner: "@cockpit"
    project: "cockpit-preview"
    preserve_project: True
    actions:
      post-upstream-clone: make cockpit-machines.spec
      # HACK: tarball for releases (copr_build, koji, etc.), copying spec's Source0; this
      # really should be the default, see https://github.com/packit/packit-service/issues/1505
      fix-spec-file:
        - sh -exc "curl -L --fail -O https://github.com/cockpit-project/${PACKIT_UPSTREAM_PACKAGE_NAME}/releases/download/${PACKIT_PROJECT_VERSION}/${PACKIT_PROJECT_NAME_VERSION}.tar.xz"
        - sh -exc "curl -L --fail -O https://github.com/cockpit-project/${PACKIT_UPSTREAM_PACKAGE_NAME}/releases/download/${PACKIT_PROJECT_VERSION}/${PACKIT_UPSTREAM_PACKAGE_NAME}-node-${PACKIT_PROJECT_VERSION}.tar.xz"

  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-42
      - fedora-43
      - fedora-development

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-42
      - fedora-43
      - fedora-development

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      # rawhide updates are created automatically
      - fedora-42
      - fedora-43
