specfile_path: cockpit-machines.spec
synced_files:
  - cockpit-machines.spec
upstream_package_name: cockpit-machines
downstream_package_name: cockpit-machines
actions:
  post-upstream-clone: make cockpit-machines.spec
  create-archive: test/download-dist --wait
jobs:
  - job: tests
    trigger: pull_request
    metadata:
      targets:
      - fedora-33
