upstream_project_url: https://github.com/cockpit-project/cockpit-machines
# enable notification of failed downstream jobs as issues
issue_repository: https://github.com/cockpit-project/cockpit-machines
specfile_path: cockpit-machines.spec
upstream_package_name: cockpit-machines
downstream_package_name: cockpit-machines
# use the nicely formatted release description from our upstream release, instead of git shortlog
copy_upstream_release_description: true

srpm_build_deps:
- npm
- make

actions:
  post-upstream-clone: make cockpit-machines.spec
  create-archive: make dist

jobs:
  - job: copr_build
    trigger: pull_request
    # implicitly defined by "tests" job, no extra build-only targets
    targets: []

  - job: tests
    trigger: pull_request
    targets:
      - fedora-41
      # https://pagure.io/fedora-infrastructure/issue/12389
      # - fedora-42
      - fedora-rawhide
      - centos-stream-9
      - centos-stream-10

  - job: copr_build
    trigger: release
    owner: "@cockpit"
    project: "cockpit-preview"
    preserve_project: True
    actions:
      post-upstream-clone: make cockpit-machines.spec
      # HACK: tarball for releases (copr_build, koji, etc.), copying spec's Source0; this
      # really should be the default, see https://github.com/packit/packit-service/issues/1505
      create-archive:
        - sh -exc "curl -L -O https://github.com/cockpit-project/cockpit-machines/releases/download/${PACKIT_PROJECT_VERSION}/${PACKIT_PROJECT_NAME_VERSION}.tar.xz"
        - sh -exc "ls ${PACKIT_PROJECT_NAME_VERSION}.tar.xz"

  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-41
      - fedora-42
      - fedora-development

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-41
      - fedora-42
      - fedora-development

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      # rawhide updates are created automatically
      - fedora-41
      - fedora-42
