specfile_path: cockpit-machines.spec
synced_files:
  - cockpit-machines.spec
upstream_package_name: cockpit-machines
downstream_package_name: cockpit-machines
srpm_build_deps:
- npm
- make
actions:
  post-upstream-clone: make cockpit-machines.spec
  create-archive:
    - make dist DOWNLOAD_DIST_OPTIONS=--wait FORCE_DOWNLOAD_DIST=1
    - rm -f test/common/sizzle.js
    - find -name 'cockpit-machines-*.tar.xz'
jobs:
  - job: tests
    trigger: pull_request
    metadata:
      targets:
      - fedora-35
      - fedora-36
      - fedora-rawhide
      - centos-stream-8
      - centos-stream-9

  - job: copr_build
    trigger: release
    metadata:
      owner: "@cockpit"
      project: "cockpit-preview"
      preserve_project: True
      targets:
      - fedora-35
      - fedora-36
      - fedora-development
      - centos-stream-8-x86_64
      - centos-stream-9-x86_64
    actions:
      post-upstream-clone: make cockpit-machines.spec
      # HACK: tarball for releases (copr_build, koji, etc.), copying spec's Source0; this
      # really should be the default, see https://github.com/packit/packit-service/issues/1505
      create-archive:
        - sh -exc "curl -L -O https://github.com/cockpit-project/cockpit-machines/releases/download/${PACKIT_PROJECT_VERSION}/${PACKIT_PROJECT_NAME_VERSION}.tar.xz"
        - sh -exc "ls ${PACKIT_PROJECT_NAME_VERSION}.tar.xz"
