upstream_project_url: https://github.com/cockpit-project/cockpit-machines
# enable notification of failed downstream jobs as issues
issue_repository: https://github.com/cockpit-project/cockpit-machines
specfile_path: cockpit-machines.spec
upstream_package_name: cockpit-machines
downstream_package_name: cockpit-machines
# use the nicely formatted release description from our upstream release, instead of git shortlog
copy_upstream_release_description: true

packages:
  cockpit-machines-fedora:
    specfile_path: cockpit-machines.spec
  cockpit-machines-centos:
    specfile_path: cockpit-machines.spec
    pkg_tool: centpkg

srpm_build_deps:
- npm
- make

actions:
  post-upstream-clone: make cockpit-machines.spec
  create-archive: make dist

jobs:
  - job: copr_build
    trigger: pull_request
    packages: [cockpit-machines-fedora]
    targets:
    - fedora-39
    - fedora-40
    - fedora-development

  - job: copr_build
    trigger: pull_request
    packages: [cockpit-machines-centos]
    targets:
    - centos-stream-9
    - centos-stream-10

  - job: tests
    packages: [cockpit-machines-fedora]
    trigger: pull_request
    targets:
      - fedora-39
      - fedora-40
      - fedora-development

  - job: tests
    packages: [cockpit-machines-centos]
    trigger: pull_request
    targets:
      - centos-stream-9
      - centos-stream-10

  - job: copr_build
    trigger: release
    owner: "@cockpit"
    project: "cockpit-preview"
    preserve_project: True
    actions:
      post-upstream-clone: make cockpit-machines.spec
      # HACK: tarball for releases (copr_build, koji, etc.), copying spec's Source0; this
      # really should be the default, see https://github.com/packit/packit-service/issues/1505
      create-archive:
        - sh -exc "curl -L -O https://github.com/cockpit-project/cockpit-machines/releases/download/${PACKIT_PROJECT_VERSION}/${PACKIT_PROJECT_NAME_VERSION}.tar.xz"
        - sh -exc "ls ${PACKIT_PROJECT_NAME_VERSION}.tar.xz"

  - job: propose_downstream
    trigger: release
    packages: [cockpit-machines-fedora]
    dist_git_branches:
      - fedora-development
      - fedora-39
      - fedora-40

  - job: propose_downstream
    trigger: release
    packages: [cockpit-machines-centos]
    dist_git_branches:
      - c9s

  - job: koji_build
    trigger: commit
    packages: [cockpit-machines-fedora]
    dist_git_branches:
      - fedora-development
      - fedora-39
      - fedora-40

  - job: bodhi_update
    trigger: commit
    packages: [cockpit-machines-fedora]
    dist_git_branches:
      # rawhide updates are created automatically
      - fedora-39
      - fedora-40
