upstream_project_url: https://github.com/cockpit-project/cockpit-machines
# enable notification of failed downstream jobs as issues
issue_repository: https://github.com/cockpit-project/cockpit-machines
specfile_path: cockpit-machines.spec
upstream_package_name: cockpit-machines
downstream_package_name: cockpit-machines
# use the nicely formatted release description from our upstream release, instead of git shortlog
copy_upstream_release_description: true

srpm_build_deps:
- npm
- make

actions:
  post-upstream-clone: make cockpit-machines.spec
  create-archive: make dist

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
    - centos-stream-8

  - job: tests
    trigger: pull_request
    targets:
      - centos-stream-8
