name: build-dist
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          # need this to also fetch tags
          fetch-depth: 0

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends npm make gettext

      - name: Build
        run: NODE_ENV=production make

      - name: Create dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/
            package-lock.json
          retention-days: 1
