name: build-dist
on:
  pull_request:
  push:
    branches: [main]
    tags:
      # this is a glob, not a regexp
      - '[0-9]*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          # need this to also fetch tags
          fetch-depth: 0
          # avoid checking out the default pull/NNN/head ref, as that gives
          # mismatching SHAs in generated tarballs
          ref: "${{ github.event.pull_request.head.sha || github.sha }}"

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends npm make gettext sassc

      - name: Build dist tarball
        run: make dist-gzip

      - name: Create dist tarball artifact
        uses: actions/upload-artifact@v2
        with:
          # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
          # for pull_requests, use HEAD of the proposed branch, for pushes to origin the current SHA
          name: "dist-${{ github.event.pull_request.head.sha || github.sha }}"
          path: cockpit-machines-*.tar.gz
          retention-days: 7
