name: npm-update
on:
  schedule:
    - cron: '0 2 * * 1,4'
  # can be run manually on https://github.com/cockpit-project/cockpit-machines/actions
  workflow_dispatch:
jobs:
  npm-update:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y npm make

      - name: Set up configuration and secrets
        run: |
          printf '[user]\n\tname = Cockpit Project\n\temail=cockpituous@gmail.com\n' > ~/.gitconfig
          echo '${{ secrets.COCKPITUOUS_TOKEN }}' > ~/.config/github-token

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          # the default GITHUB_TOKEN would override our ~/.git-credentials from above
          token: '${{ secrets.COCKPITUOUS_TOKEN }}'

      - name: Run npm-update bot
        run: |
          make bots
          bots/npm-update
