name: publish-dist
on:
  workflow_run:
    workflows: build-dist
    types: [completed]

jobs:
  run:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pull-requests: none
    environment: cockpit-machines-dist
    env:
      DIST_REPO: ssh://git@github.com/${{ github.repository }}-dist.git
    steps:
      - name: Download build-dist artifacts
        # 2.14.0; if you update this, audit the diff and ensure that it does not leak/abuse secrets
        uses: dawidd6/action-download-artifact@b9571484721e8187f1fd08147b497129f8972c74
        with:
          name: dist
          workflow: build-dist
          run_id: ${{ github.event.workflow_run.id }}
          path: dist-repo

      - name: Set up configuration
        run: |
          printf '[user]\n\tname = Cockpit Project\n\temail=cockpituous@gmail.com\n' > ~/.gitconfig

      - name: Commit to dist repo
        run: |
          set -ex
          cd dist-repo
          git init
          git add .
          git commit -m 'Build for ${{ github.event.workflow_run.head_sha }}'
          tag='sha-${{ github.event.workflow_run.head_sha }}'
          git tag "$tag"

          eval $(ssh-agent)
          ssh-add - <<< '${{ secrets.DEPLOY_KEY }}'

          git push "$DIST_REPO" "$tag"

          ssh-add -D
          ssh-agent -k
