name: publish-dist
on:
  workflow_run:
    workflows: build-dist
    types: [completed]

jobs:
  run:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Download build-dist artifacts
        # 2.14.0; if you update this, audit the diff and ensure that it does not leak/abuse secrets
        uses: dawidd6/action-download-artifact@b9571484721e8187f1fd08147b497129f8972c74
        with:
          name: dist
          workflow: build-dist
          run_id: ${{ github.event.workflow_run.id }}

      - name: Set up configuration and secrets
        run: |
          printf '[user]\n\tname = Cockpit Project\n\temail=cockpituous@gmail.com\n' > ~/.gitconfig
          echo '${{ secrets.COCKPITUOUS_TOKEN }}' > ~/.config/github-token
          # we push to -dist repo via https://github.com, that needs our cockpituous token
          git config --global credential.helper store
          echo 'https://token:${{ secrets.COCKPITUOUS_TOKEN }}@github.com' >> ~/.git-credentials

      - name: Commit to dist repo
        run: |
          set -ex

          mkdir dist-repo
          cd dist-repo
          git init
          cp -r ../dist/ ../package-lock.json .

          git add .
          git commit -m "Build for ${{ github.event.workflow_run.head_sha }}"
          tag="sha-${{ github.event.workflow_run.head_sha }}"
          git tag "$tag"

          git push https://github.com/${{ github.repository }}-dist.git "$tag"

      - name: Trigger integration tests for PRs
        run: |
          if ! grep -q '"pull_request"' event.json; then
              echo "build-dist event was not a pull request"
              exit 0
          fi
          # support running this from forks
          if [ -z '${{ secrets.AMQP_CLIENT_KEY }}' ]; then
              echo "No AMQP secrets, skipping tests-scan"
              exit 0
          fi

          pip install pika

          git clone --depth=1 https://github.com/cockpit-project/bots

          # tests-scan does not currently have a --secrets-dir option
          sudo mkdir -p /run/secrets/webhook
          echo '${{ secrets.COCKPIT_CA_PEM }}' | sudo dd status=none of=/run/secrets/webhook/ca.pem
          echo '${{ secrets.AMQP_CLIENT_PEM }}' | sudo dd status=none of=/run/secrets/webhook/amqp-client.pem
          echo '${{ secrets.AMQP_CLIENT_KEY }}' | sudo dd status=none of=/run/secrets/webhook/amqp-client.key

          # FIXME: make this nicer in tests-scan
          AMQP_SERVER=$(PYTHONPATH=bots python3 -c 'from task.distributed_queue import *; print(DEFAULT_AMQP_SERVER)')
          GITHUB_BASE=${{ github.repository }} bots/tests-scan -d --pull-data "$(cat event.json)" --amqp "$AMQP_SERVER"
